name: eks_khedamtresan
description: "Emdad khodro Saipa - Khedmatresan."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  build_runner: ^2.4.8
  freezed: ^2.4.7
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

