name: network_module
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  dio_cache_interceptor: ^3.5.0
  logger: ^2.0.2+1
  utility:
    path: ../utility

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8

